# Kubernetes api version
apiVersion: v1
# Type of kubernetes resource: Pod, Deployment, Service
kind: Service
# Metadata about the service
metadata:
  name: nginx-clusterip
spec:
  # Type of service such as clusterIp, nodeport, loadbalancer
  type: ClusterIP
  selector:
    app: my-nginx
  ports:
    - port: 8080
      targetPort: 80
