# Kubernetes api version
apiVersion: v1
# Type of kubernetes resource: Pod, Deployment, Service
kind: Service
# Metadata about the service
metadata:
  name: nginx-clusterip
spec:
  # Type of service such as clusterIp, nodeport, loadbalancer
  type: ClusterIP
  selector:
    # Link service to POD. Need the same POD label
    app: my-nginx
  ports:
      # port: Port on the service
    - port: 8080
      # targetPort: Port running on POD (docker container)
      targetPort: 80
